<?php

namespace ODE\DatasetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CitationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitationsRepository extends EntityRepository
{
}
