<?php

namespace ODE\DatasetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KeywordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordsRepository extends EntityRepository
{
}
